name: Waka Readme

on:
  workflow_dispatch:
  schedule:
    - cron: '45 18 * * *'

jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_PROJECTS: "False"
          SHOW_LANGUAGE_PER_REPO: "False"  
          SHOW_LINES_OF_CODE: "True"
          LOCALE: "en"
